baseURL = "/"
languageCode = "fr-fr"
title = "MeLuv Recipes"
defaultContentLanguage = "fr"
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]
relativeURLs = true
canonifyURLs = false

[params]
tagline = "Recettes Cooklang"
description = "Collection de recettes Cooklang avec une page statique par recette."
